/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sahti.GUI.Login;

import MailingAPI.Mailer;
import MailingAPI.PasswordGenerator;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import org.controlsfx.control.Notifications;
import sahti.services.ResetPassword;

/**
 * FXML Controller class
 *
 * @author Rayen
 */
public class ResetPasswdController implements Initializable {

    @FXML
    private TextField txtmailreset;
    @FXML
    private Button idreset;

    /**
     * Initializes the controller class.
     */
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        // TODO
    }

    @FXML
    private void ResetMail(ActionEvent event) {

        String mail = txtmailreset.getText();

        if (mail.isEmpty()) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("Email must be filled properly !");
            alert.setContentText("Try again to recover your password");
            alert.showAndWait();
        }
        else {

            //update password here 
            ResetPassword r = new ResetPassword();
            String pwd = PasswordGenerator.generateStrongPassword();
            if (r.ClientPwd(mail, pwd) == true) {
                Mailer.send("noreplysahti@gmail.com", "rwtlwppcxycwhwfa", mail, "Password reset request ", "Hello " + mail + "\n This is your new password generated by SAHTI Application : \n  " + pwd + " \n The above is a temporary password. We highly recommend that you update the password after you log in successfully. \n Thanks, ");
                //notification
                Notifications notificationBuilder = Notifications.create()
                        .title("Notification").text("Password sent to your email").graphic(null).hideAfter(javafx.util.Duration.seconds(5))
                        .position(Pos.BOTTOM_RIGHT)
                        .onAction((ActionEvent event1) -> {
                            System.out.println("Password sent to your mail ");
                });
                notificationBuilder.darkStyle();
                notificationBuilder.show();

            }
            else if (r.EntraineurPwd(mail, pwd) == true) {
                Mailer.send("noreplysahti@gmail.com", "rwtlwppcxycwhwfa", mail, "Password reset request ", "Hello " + mail + "\n This is your new password generated by SAHTI Application : \n  " + pwd + " \n The above is a temporary password. We highly recommend that you update the password after you log in successfully. \n Thanks, ");

                Notifications notificationBuilder = Notifications.create()
                        .title("Notification").text("Password sent to your email").graphic(null).hideAfter(javafx.util.Duration.seconds(5))
                        .position(Pos.BOTTOM_RIGHT)
                        .onAction(new EventHandler<ActionEvent>() {
                            public void handle(ActionEvent event) {
                                System.out.println("Password sent to your mail ");
                            }
                        }
                        );
                notificationBuilder.darkStyle();
                notificationBuilder.show();

            }
            else if (r.NutritionistePwd(mail, pwd) == true) {
                Mailer.send("noreplysahti@gmail.com", "rwtlwppcxycwhwfa", mail, "Password reset request ", "Hello " + mail + "\n This is your new password generated by SAHTI Application : \n  " + pwd + " \n The above is a temporary password. We highly recommend that you update the password after you log in successfully. \n Thanks, ");
             
                Notifications notificationBuilder = Notifications.create()
                        .title("Notification").text("Password sent to your email").graphic(null).hideAfter(javafx.util.Duration.seconds(5))
                        .position(Pos.BOTTOM_RIGHT)
                        .onAction(new EventHandler<ActionEvent>() {
                            public void handle(ActionEvent event) {
                                System.out.println("Password sent to your mail ");
                            }
                        }
                        );
                notificationBuilder.darkStyle();
                notificationBuilder.show();
                
            }
            else {
                System.out.println("Somthing went wrong please try again !");
            }

        }

        FXMLLoader loader = new FXMLLoader(getClass().getResource("Login.fxml"));

        Parent root;
        Stage stage;
        try {
            root = loader.load();
            stage = (Stage) idreset.getScene().getWindow();
            Scene scene = new Scene(root);
            stage.setScene(scene);
            stage.show();
        }
        catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
    }

}
